##############################################################################################
#
# Travis CI configuration file
# 
# Set the required secrets in the build settings of the project:
#   - BINTRAY_USER
#   - BINTRAY_API_KEY
#   - GITHUB_API_KEY
#
##############################################################################################

env:
  global:
  - PACKAGE_NAME=openc2x
  - BINTRAY_REPO_NAME=debian
  - BINTRAY_LICENSE=ISC
  matrix:
  - ARCHITECTURE=trusty/amd64
  - ARCHITECTURE=trusty/i386
  
sudo: required
services:
  - docker
    
before_install:
  - docker build -t $ARCHITECTURE $ARCHITECTURE

script:
  - export NUMBER=${TRAVIS_BUILD_NUMBER}
  - export BUILD_VERSION=1.$NUMBER
  - export ARCH=$(basename $ARCHITECTURE)
  - export DIST=$(dirname $ARCHITECTURE)
  - docker run -v $PWD:/tmp $ARCHITECTURE /bin/sh -c "cd /tmp; cmake .; make -j1; make package"
  - cp ${PACKAGE_NAME}-${BUILD_VERSION}-Linux.deb ${PACKAGE_NAME}-${BUILD_VERSION}-${DIST}_${ARCH}.deb 

before_deploy:
  # Set the packages name and details in the descriptor file
  - sed -i "s/__NAME__/$PACKAGE_NAME/g" bintray-descriptor.json
  - sed -i "s/__REPO_NAME__/$BINTRAY_REPO_NAME/g" bintray-descriptor.json
  - sed -i "s/__SUBJECT__/$BINTRAY_USER/g" bintray-descriptor.json
  - sed -i "s/__LICENSE__/$BINTRAY_LICENSE/g" bintray-descriptor.json
  - sed -i "s/__VERSION__/$BUILD_VERSION/g" bintray-descriptor.json
  - sed -i "s/__ARCHITECTURE__/$ARCH/g" bintray-descriptor.json
  - sed -i "s/__DIST__/$DIST/g" bintray-descriptor.json
  - git tag "${BUILD_VERSION}" || true

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: ${PACKAGE_NAME}-*-${DIST}_${ARCH}.deb 
    skip_cleanup: true
    on:
      branch: master
  - provider: bintray
    file: bintray-descriptor.json
    user: $BINTRAY_USER
    key: $BINTRAY_API_KEY
    skip_cleanup: true
    on:
      branch: master
